# Generated by Django 4.1.1 on 2022-11-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_author_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Fecha de edición"
            ),
        ),
    ]
